#!/bin/bash
set -e

# Synchronize HDP core
echo "HDP directory"
mkdir -p /var/www/html/HDP/centos6/2.x/updates/2.1.4.0
echo "HDP reposync"
reposync -p /var/www/html/HDP/centos6/2.x/updates/2.1.4.0 --repoid=HDP-2.1.4.0
echo "HDP repo"
createrepo /var/www/html/HDP/centos6/2.x/updates/2.1.4.0
# Synchronize HDP utils
mkdir -p /var/www/html/HDP-UTILS-1.1.0.17/repos/centos6
reposync -p /var/www/html/HDP-UTILS-1.1.0.17/repos/centos6 --repoid=HDP-UTILS-1.1.0.17
createrepo /var/www/html/HDP-UTILS-1.1.0.17/repos/centos6
