#!/bin/bash
set -e

mkdir -p /var/www/html/centos/6/x86_64
reposync -p /var/www/html/centos/6/os/x86_64 --repoid=base
createrepo /var/www/html/centos/6/os/x86_64
reposync -p /var/www/html/centos/6/updates/x86_64 --repoid=updates
createrepo /var/www/html/centos/6/updates/x86_64
reposync -p /var/www/html/centos/6/extras/x86_64 --repoid=extras
createrepo /var/www/html/centos/6/extras/x86_64
reposync -p /var/www/html/centos/6/centosplus/x86_64 --repoid=centosplus
createrepo /var/www/html/centos/6/centosplus/x86_64
