// Generated by CoffeeScript 1.9.0
var arg, i, name, parameters, params, port, repo, repos, url, util;

util = require('util');

parameters = require('parameters');

repos = require('./repos');

params = parameters({
  name: 'repos',
  description: 'Install and sync RHEL/CentOS repositories',
  commands: [
    {
      name: 'list',
      description: 'list all the installed repositories',
      options: [
        {
          name: 'repo',
          type: 'array',
          shortcut: 'r',
          description: 'repo name filter(s)'
        }
      ]
    }, {
      name: 'sync',
      description: 'initialize local repo with Docker container',
      options: [
        {
          name: 'repo',
          type: 'array',
          shortcut: 'r',
          required: true,
          description: 'repo(s) to initialize'
        }, {
          name: 'url',
          type: 'array',
          shortcut: 'u',
          required: false,
          description: 'the url(s) of the repo(s)'
        }
      ]
    }, {
      name: 'start',
      description: 'Start Repo server(s) with Docker',
      options: [
        {
          name: 'repo',
          type: 'array',
          shortcut: 'r',
          description: 'the repo(s) to start. All by default'
        }, {
          name: 'port',
          shortcut: 'p',
          type: 'array',
          description: 'force port value'
        }
      ]
    }, {
      name: 'stop',
      description: 'Stop Repo server(s) with Docker',
      options: [
        {
          name: 'repo',
          type: 'array',
          shortcut: 'r',
          description: 'the repo(s) to stop. All by default'
        }
      ]
    }, {
      name: 'remove',
      description: 'Delete a repo',
      options: [
        {
          name: 'repo',
          shortcut: 'r',
          type: 'array',
          required: true,
          description: 'the repo(s) to delete'
        }
      ]
    }
  ]
});

arg = params.parse();

switch (arg.command) {
  case 'help':
    console.log(params.help(arg.name));
    break;
  case 'list':
    repos.list(arg.repo, function(err, repos) {
      var repo, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = repos.length; _i < _len; _i++) {
        repo = repos[_i];
        process.stdout.write(repo.name);
        process.stdout.write(" [" + repo.port + "]");
        if (repo.docker.status) {
          process.stdout.write(" " + repo.docker.status);
        }
        if (!repo.docker.status) {
          process.stdout.write(" Not registered");
        }
        _results.push(process.stdout.write('\n'));
      }
      return _results;
    });
    break;
  case 'sync':
    repo = arg.repo, url = arg.url;
    if (url == null) {
      url = [];
    }
    if (url.length && repo.length !== url.length) {
      throw Error("Incoherent Arguments Length");
    }
    repo = (function() {
      var _i, _len, _results;
      _results = [];
      for (i = _i = 0, _len = repo.length; _i < _len; i = ++_i) {
        name = repo[i];
        _results.push({
          name: name,
          url: url[i]
        });
      }
      return _results;
    })();
    repos.sync(repo, function(err) {
      if (err) {
        return console.log(err);
      }
    });
    break;
  case 'start':
    repo = arg.repo, port = arg.port;
    if (repo == null) {
      repo = [];
    }
    if (port == null) {
      port = [];
    }
    if (port.length && repo.length !== port.length) {
      throw Error("Incoherent Arguments Length");
    }
    repo = (function() {
      var _i, _len, _results;
      _results = [];
      for (i = _i = 0, _len = repo.length; _i < _len; i = ++_i) {
        name = repo[i];
        _results.push({
          name: name,
          port: port[i]
        });
      }
      return _results;
    })();
    repos.start(repo, function(err) {
      if (err) {
        return console.log(err);
      }
    });
    break;
  case 'stop':
    repos.stop(arg.repo, function(err) {
      if (err) {
        return console.log(err);
      }
    });
    break;
  case 'remove':
    repos.remove(arg.repo, function(err) {
      if (err) {
        return console.log(err);
      }
    });
}
