// Generated by CoffeeScript 1.9.1
var exec;

exec = require('./exec');

module.exports = function(debug) {
  return {
    sync: function(repopath, callback) {
      return exec("if command -v boot2docker; then boot2docker up && $(boot2docker shellinit); fi\ndocker run -v " + repopath + ":/var/ryba --rm=true ryba_repos/syncer", debug, callback);
    },
    start: function(repo, callback) {
      return exec("if command -v boot2docker; then boot2docker up && $(boot2docker shellinit); fi\ndocker start " + repo, debug, callback);
    },
    stop: function(repo, callback) {
      return exec("if command -v boot2docker; then boot2docker up && $(boot2docker shellinit); fi\ndocker stop " + repo, debug, callback);
    },
    rm: function(repo, callback) {
      return exec("if command -v boot2docker; then boot2docker up && $(boot2docker shellinit); fi\ndocker rm " + repo, debug, callback);
    },
    run: function(repo, pubdir, callback) {
      if (!((repo.name != null) && (repo.port != null))) {
        throw Error('Invalid arguments');
      }
      return exec("if command -v boot2docker; then boot2docker up && $(boot2docker shellinit); fi\ndocker run -d --name=" + repo.name + " -v " + pubdir + "/" + repo.name + ":/usr/local/apache2/htdocs/ -p " + repo.port + ":80 httpd", debug, callback);
    }
  };
};
