// Generated by CoffeeScript 1.9.1
var exec, watercolor;

exec = require('child_process').exec;

watercolor = require('watercolor');

module.exports = function(cmd, debug, callback) {
  var child, w;
  child = exec(cmd, callback);
  if (debug) {
    w = watercolor({
      color: 'green'
    });
    w.pipe(process.stdout);
    w.write('\n');
    w.write(cmd);
    w.write('\n\n');
    child.stdout.pipe(watercolor({
      color: 'cyan'
    })).pipe(process.stdout);
    return child.stderr.pipe(watercolor({
      color: 'magenta'
    })).pipe(process.stderr);
  }
};
